import {test,chromium,expect} from "@playwright/test";import fs from "node:fs";import path from "node:path";const ROOT=process.cwd(),TARGET=process.env.E2E_BASE_URL||'http://127.0.0.1:4174';const OUTPUT=path.join(ROOT,'.kb-pilot','professional');fs.mkdirSync(OUTPUT,{recursive:true});expect.configure({timeout:25000});
test('editor profissional e cinco prévias locais de leitura',async()=>{test.skip(process.env.KB_E2E_PILOT!=='1','Requer piloto local e lote importado.');test.setTimeout(300_000);if(!['127.0.0.1','localhost'].includes(new URL(TARGET).hostname))throw Error('Piloto somente local.');const browser=await chromium.launch({headless:false});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());try{
 await page.goto(TARGET+'/bc/gestao');await page.getByRole('button',{name:'Autor piloto',exact:true}).click();await page.getByRole('button',{name:'Criar artigo',exact:true}).click();await expect(page.locator('.tiptap')).toHaveCount(4);
 const title='Editor profissional '+Date.now();await page.getByLabel('Título',{exact:true}).fill(title);await page.getByLabel('Resumo',{exact:true}).fill('Validação de alinhamento, cores, tamanho, destaque e controles de edição.');await page.getByLabel('Produto',{exact:true}).fill('DOC-Windows');
 const section=page.locator('.kb-guided-section').first();const text=section.locator('.tiptap');await text.fill('Formatação profissional preservada em todos os modos de edição.');await text.press('Control+a');
 await section.getByRole('button',{name:'Negrito',exact:true}).click();await section.getByRole('button',{name:'Sublinhado',exact:true}).click();await section.getByLabel('Tamanho em Objetivo',{exact:true}).selectOption('18px');await section.getByRole('button',{name:'Justificar',exact:true}).click();await section.getByRole('button',{name:'Cor do texto',exact:true}).click();await section.getByRole('button',{name:'Texto DeMaria',exact:true}).click();await section.getByRole('button',{name:'Destacar texto',exact:true}).click();await section.getByRole('button',{name:'Destaque Amarelo',exact:true}).click();
 await section.getByRole('button',{name:'Inserir ou editar link',exact:true}).click();await section.getByLabel('Endereço do link',{exact:true}).fill('https://demaria.com.br');await section.getByRole('button',{name:'Aplicar link',exact:true}).click();
 const steps=page.locator('.kb-guided-section').nth(2);await steps.locator('.tiptap').fill('Procedimento com tabela nativa.');await steps.getByRole('button',{name:'Tabela',exact:true}).click();await steps.getByRole('button',{name:'Tabela 3×3',exact:true}).click();await expect(steps.locator('table tr')).toHaveCount(3);await steps.locator('table td').first().click();await steps.getByRole('button',{name:'Tabela',exact:true}).click();await steps.getByRole('button',{name:'Linha abaixo',exact:true}).click();await expect(steps.locator('table tr')).toHaveCount(4);await steps.getByRole('button',{name:'Fechar ferramentas',exact:true}).click();
 await expect(section.getByRole('button',{name:'Justificar',exact:true})).toHaveAttribute('aria-pressed','true');await expect(text.locator('p')).toHaveCSS('text-align','justify');await expect(text.locator('mark')).toBeVisible();await section.locator('.kb-editor-tools').screenshot({path:path.join(OUTPUT,'toolbar.png')});await page.screenshot({path:path.join(OUTPUT,'editor-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();await expect(page.locator('.kb-editor-top')).toContainText('Versão 2');const slug=(await page.getByRole('link',{name:'Link permanente',exact:true}).getAttribute('href')).split('/').pop();const data=await (await page.request.get(TARGET+'/api/kb?editorial=1')).json();const id=data.articles.find(a=>a.slug===slug).id;const before=await (await page.request.get(TARGET+'/api/kb/articles/'+id)).json();
 expect(before.document.sections[0].content.content[0].attrs.textAlign).toBe('justify');const marks=before.document.sections[0].content.content[0].content[0].marks;expect(marks.find(m=>m.type==='textStyle').attrs).toEqual({color:'#087b80',fontSize:'18px'});expect(marks.find(m=>m.type==='highlight').attrs.color).toBe('#fef08a');
 for(let n=0;n<5;n++){await page.getByRole('button',{name:'Código HTML',exact:true}).click();await expect(page.getByRole('textbox',{name:'Código HTML',exact:true})).toContainText('text-align:justify');await page.getByRole('button',{name:'Visual',exact:true}).click();await expect(page.locator('.tiptap')).toHaveCount(4);}
 await page.getByRole('button',{name:'Prévia',exact:true}).click();await expect(page.locator('.kb-content mark')).toBeVisible();await expect(page.locator('.kb-content p').first()).toHaveCSS('text-align','justify');await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();await expect(page.locator('.kb-editor-top')).toContainText('Versão 3');const after=await (await page.request.get(TARGET+'/api/kb/articles/'+id)).json();expect(after.document).toEqual(before.document);
 await page.getByRole('button',{name:'Visual',exact:true}).click();await page.setViewportSize({width:375,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:path.join(OUTPUT,'editor-mobile.png'),fullPage:true});
 await page.goto(TARGET+'/bc/previas');await expect(page.locator('.kb-results h2 a')).toHaveCount(5);const links=await page.locator('.kb-results h2 a').evaluateAll(es=>es.map(e=>({title:e.textContent,href:e.getAttribute('href')})));const results=[];
 for(const link of links){await page.goto(TARGET+link.href);await expect(page.locator('.kb-reader h1')).toHaveText(link.title);await expect(page.locator('.kb-image-button img').first()).toBeVisible();await expect.poll(()=>page.locator('.kb-image-button img').count()).toBe([5,3,4,5,6][results.length]);const first=page.locator('.kb-image-button').first();await first.focus();await page.keyboard.press('Enter');await expect(page.locator('dialog[open]')).toBeVisible();await page.keyboard.press('Escape');await expect(first).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:path.join(OUTPUT,'preview-'+results.length+'.png'),fullPage:true});results.push({...link,mobileZoom:true});}
 await page.setViewportSize({width:1440,height:1000});await page.goto(TARGET+'/bc/previas');await page.screenshot({path:path.join(OUTPUT,'preview-index.png'),fullPage:true});expect(errors).toEqual([]);fs.writeFileSync(path.join(OUTPUT,'results.json'),JSON.stringify({editor:{formatting:true,htmlCycles:5,jsonUnchanged:true,mobileOverflow:false},previews:results,errors},null,2));console.log('PASS: editor profissional; cores/alinhamento/destaque/tamanho; 5 ciclos; 5 prévias com imagens e zoom mobile.');
 }catch(e){await page.screenshot({path:path.join(OUTPUT,'failure.png'),fullPage:true});console.error(await page.locator('body').innerText());throw e;}finally{await browser.close();}});
