import { PGlite } from "@electric-sql/pglite";
import { beforeAll,afterAll,it,expect } from "vitest";
import { initializeLocal,asLocal,pilotProfiles } from "./local-db";
import { newDocument,identifyBlocks } from "./document";
const db=new PGlite(),author=pilotProfiles[0].id,admin=pilotProfiles[1].id;
const rpc=(actor:string,cmd:object)=>asLocal(db,actor,async tx=>(await tx.query<{id:string}>("select kb_mutate($1::jsonb) id",[JSON.stringify(cmd)])).rows[0].id);
const record=(slug:string,hash="a".repeat(64))=>db.query<{r:{legacy:number|null;new:number;total:number|null}}>("select kb_record_view($1,$2) r",[slug,hash]).then(r=>r.rows[0].r);
let aid:string;
beforeAll(async()=>{await initializeLocal(db);const d=newDocument();d.metadata={...d.metadata,title:"Procedimento de teste",summary:"Resumo completo de teste",product:"DOC-Windows"};d.sections.forEach(s=>s.content=identifyBlocks({type:"doc",content:[{type:"paragraph",content:[{type:"text",text:"Instruções completas para teste."}]}]}));aid=await rpc(author,{action:"create",document:d,slug:"teste-contador"});await db.query("update kb_articles set origin_wp_id=42,origin_author_name='Autor WordPress',origin_created_at='2019-01-02',origin_modified_at='2020-01-02',origin_views=34 where id=$1",[aid]);},30000);
afterAll(()=>db.close());
it("preserva autor, datas, pesquisa e contador histórico em rascunho",async()=>{const r=await asLocal(db,author,async tx=>(await tx.query<{r:{articles:{author_name:string;created_at:string;views_total:number}[]}}>("select kb_editorial_index('all',1,'Autor WordPress') r")).rows[0].r);expect(r.articles[0]).toMatchObject({author_name:"Autor WordPress",views_total:34});expect(r.articles[0].created_at).toContain("2019-01-02");await expect(record("teste-contador")).rejects.toThrow();});
it("conta somente publicados, deduplica e soma legado sem permitir RPC público",async()=>{await rpc(author,{action:"submit",articleId:aid,expectedVersion:1});const sub=(await db.query<{id:string;revision_id:string}>("select id,revision_id from kb_submissions where article_id=$1",[aid])).rows[0];await rpc(admin,{action:"publish",articleId:aid,expectedVersion:2,submissionId:sub.id,revisionId:sub.revision_id,visibility:"public"});expect(await record("teste-contador")).toEqual({legacy:34,new:1,total:35});expect(await record("teste-contador")).toEqual({legacy:34,new:1,total:35});expect(await record("teste-contador","b".repeat(64))).toEqual({legacy:34,new:2,total:36});for(const actor of [null,author])await expect(asLocal(db,actor,tx=>tx.query("select kb_record_view('teste-contador',$1)",["c".repeat(64)]))).rejects.toThrow(/permission denied/);});
it("não inventa o legado ausente nem zera as novas leituras ao atualizar origem",async()=>{await db.query("update kb_articles set origin_views=null where id=$1",[aid]);expect(await record("teste-contador")).toEqual({legacy:null,new:2,total:null});await db.query("update kb_articles set origin_views=34 where id=$1",[aid]);expect(await record("teste-contador")).toEqual({legacy:34,new:2,total:36});await rpc(admin,{action:"visibility",articleId:aid,expectedVersion:3,visibility:"private"});expect((await asLocal(db,null,tx=>tx.query("select * from kb_publications where slug='teste-contador'"))).rows).toHaveLength(0);expect((await asLocal(db,author,tx=>tx.query("select * from kb_publications where slug='teste-contador'"))).rows).toHaveLength(1);});

it("deduplica requisições concorrentes e aceita uma nova leitura na hora seguinte",async()=>{const hash="d".repeat(64);const results=await Promise.all([record("teste-contador",hash),record("teste-contador",hash)]);expect(results.map(r=>r.total)).toEqual([37,37]);await db.query("update kb_article_view_events set bucket=bucket-interval '1 hour' where article_id=$1 and visitor_hash=$2",[aid,hash]);expect(await record("teste-contador",hash)).toEqual({legacy:34,new:4,total:38});});
