"use client";
import dynamic from "next/dynamic";
import { useEffect,useState } from "react";
import { newDocument,templates,type KbDocument } from "@/lib/kb/document";
import { kbJson } from "@/lib/kb/client";
import type { Detail } from "./editor";
import { KbNotices } from "./notices";
const KbEditor=dynamic(()=>import("./editor").then(m=>m.KbEditor),{ssr:false});
type Row={id:string;title:string;status:string;version:number;owner_id:string;updated_at:string};
type Me={id:string;name:string;role:string};
export function KbManagement({pilot=false}:{pilot?:boolean}){
 const [rows,setRows]=useState<Row[]>([]),[me,setMe]=useState<Me|null>(null),[article,setArticle]=useState<Detail|null>(null),[error,setError]=useState(""),[template,setTemplate]=useState<KbDocument["templateId"]>("procedimento"),[filter,setFilter]=useState("mine"),[page,setPage]=useState(1),[profiles,setProfiles]=useState<Me[]>([]),[busy,setBusy]=useState(false);
 const load=async()=>{try{const r=await kbJson<{articles:Row[];me:Me}>(`/api/kb?editorial=1&pagina=${page}&filter=${filter}`);setRows(r.articles);setMe(r.me);setError("");}catch(e){setError((e as Error).message);setRows([]);setMe(null);}};
 useEffect(()=>{void load();},[page,filter]);
 useEffect(()=>{if(pilot)void kbJson<{profiles:Me[]}>("/api/kb/pilot").then(r=>setProfiles(r.profiles)).catch(()=>{});},[pilot]);
 const open=async(id:string)=>{setBusy(true);try{setArticle(await kbJson<Detail>(`/api/kb/articles/${id}`));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <div className="kb kb-management">{pilot?<section className="kb-pilot"><h2>Homologação local</h2><p>Contas sintéticas isoladas. Este acesso é desativado em produção.</p>{profiles.map(p=><button key={p.id} onClick={async()=>{await kbJson("/api/kb/pilot",{method:"POST",body:JSON.stringify({id:p.id})});setArticle(null);await load();}}>{p.name}</button>)}<button onClick={async()=>{await kbJson("/api/kb/pilot",{method:"POST",body:JSON.stringify({id:null})});setArticle(null);await load();}}>Visitante</button></section>:null}{me?<KbNotices refreshKey={`${me.id}-${article?.version||0}`} onOpen={id=>void open(id)}/>:null}{article?<KbEditor key={`${article.id}-${article.version}`} article={article} admin={me?.role==="admin"} onRefresh={async()=>{await open(article.id);await load();}} onBack={()=>{setArticle(null);void load();}}/>:<><p className="kb-eyebrow">BASE DE CONHECIMENTO OFICIAL</p><h1>Meus artigos e revisões</h1><p>{me?`${me.name} · ${me.role==="admin"?"Administração editorial":"Autoria"}`:"Entre com uma conta interna aprovada."}</p><p role="alert">{error}</p>{me?<><div className="kb-create"><label>Modelo institucional<select value={template} onChange={e=>setTemplate(e.target.value as KbDocument["templateId"])}>{Object.entries(templates).map(([key,t])=><option key={key} value={key}>{t.name}</option>)}</select></label><button disabled={busy} onClick={async()=>{setBusy(true);try{const r=await kbJson<{id:string}>("/api/kb",{method:"POST",body:JSON.stringify({action:"create",document:newDocument(template)})});await open(r.id);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Criar artigo</button></div><div className="kb-tabs" role="group" aria-label="Filtrar artigos">{["mine","draft","review","changes",...(me.role==="admin"?["all"]:[])].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{{mine:"Meus artigos",draft:"Rascunhos",review:"Fila de revisão",changes:"Ajustes solicitados",all:"Todos"}[f]}</button>)}</div><div className="kb-editorial-list">{rows.slice(0,20).filter(r=>filter==="all"||filter==="mine"&&r.owner_id===me.id||r.status===filter).map(r=><article key={r.id}><div><h2><button disabled={busy} onClick={()=>void open(r.id)}>{r.title||"Artigo sem título"}</button></h2><p>{{draft:"Rascunho",review:"Em revisão",changes:"Ajustes solicitados",published:"Publicado",archived:"Arquivado"}[r.status]||r.status} · v{r.version} · {new Date(r.updated_at).toLocaleDateString("pt-BR")}</p></div><span>{r.owner_id===me.id?"Seu artigo":"Revisão administrativa"}</span></article>)}</div><nav className="kb-pagination" aria-label="Páginas dos artigos"><button disabled={page===1||busy} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page}</span><button disabled={rows.length<=20||busy} onClick={()=>setPage(p=>p+1)}>Próxima</button></nav></>:null}</>}</div>;
}
